name: flutter_worldtime
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.5.1
  http: ^0.12.2
  intl: ^0.16.1
  state_notifier: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

